import { uniqueId } from "lodash";

import {
  IconAward,
  IconBoxMultiple,
  IconPoint,
  IconAlertCircle,
  IconNotes,
  IconCalendar,
  IconMail,
  IconTicket,
  IconEdit,
  IconGitMerge,
  IconCurrencyDollar,
  IconApps,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconBan,
  IconStar,
  IconMoodSmile,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderVertical,
  IconBorderTop,
  IconUserCircle,
  IconPackage,
  IconMessage2,
  IconBasket,
  IconChartLine,
  IconChartArcs,
  IconChartCandle,
  IconChartArea,
  IconChartDots,
  IconChartDonut3,
  IconChartRadar,
  IconLogin,
  IconUserPlus,
  IconRotate,
  IconBox,
  IconShoppingCart,
  IconAperture,
  IconLayout,
  IconSettings,
  IconHelp,
  IconZoomCode,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconBorderStyle2,
  IconLockAccess,
  IconAppWindow,
} from "@tabler/icons-react";

const Menuitems = [

  {
    navlabel: true,
    subheader: "Online Services",
  },
  {
    id: uniqueId(),
    title: "Shopping",
    icon: IconBasket,
    href: "/apps/ecommerce/shop"
  },
  {
    id: uniqueId(),
    title: "Store Blog",
    icon: IconChartDonut3,
    href: "/apps/blog/post",
   },
  {
    id: uniqueId(),
    title: "Store Calendar",
    icon: IconCalendar,
    href: "/apps/calendar",
  },
  {
    navlabel: true,
    subheader: "Dashboards",
  },

  {
    id: uniqueId(),
    title: "Company",
    icon: IconAperture,
    href: "/",
    chip: "New",
    chipColor: "secondary",
  },
  {
    id: uniqueId(),
    title: "Sales",
    icon: IconShoppingCart,
    href: "/dashboards/ecommerce",
  },
  {
    id: uniqueId(),
    title: "Help Desk",
    icon: IconTicket,
    href: "/apps/tickets",
  },
  {
    navlabel: true,
    subheader: "Store Metrics",
  },
  {
    id: uniqueId(),
    title: "Line",
    icon: IconChartLine,
    href: "/charts/line",
  },
  {
    id: uniqueId(),
    title: "Gradient",
    icon: IconChartArcs,
    href: "/charts/gradient",
  },
  {
    id: uniqueId(),
    title: "Area",
    icon: IconChartArea,
    href: "/charts/area",
  },
  {
    id: uniqueId(),
    title: "Candlestick",
    icon: IconChartCandle,
    href: "/charts/candlestick",
  },
  {
    id: uniqueId(),
    title: "Column",
    icon: IconChartDots,
    href: "/charts/column",
  },
  {
    id: uniqueId(),
    title: "Doughtnut & Pie",
    icon: IconChartDonut3,
    href: "/charts/doughnut",
  },
  {
    id: uniqueId(),
    title: "RadialBar & Radar",
    icon: IconChartRadar,
    href: "/charts/radialbar",
  },
];

export default Menuitems;
